Repository prgrms-web-devcourse/Team_BbungCles_Devnity_BE, pull requests merged in 2021-12, with the labels that each got.

#12 develop 브랜치에 ci/cd 적용 + slack 연동
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .gitignore
  deploy/dev/deploy.sh
  deploy/nginx.conf
  deploy/prod/deploy.sh
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/local-db.yml
Labels: 🔗 DevOps

#18 [CI/CD-4] JACOCO + Codecov 적용
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-test.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  README.md
  build.gradle
  codecov.yml
  src/main/java/com/devnity/devnity/domain/jwt/JwtConfig.java
  src/test/resources/application.yml
Labels: ⚙ chore, 🔗 DevOps

#33 [User- 15] 사용자 로그인 기능 추가
  build.gradle
  src/main/java/com/devnity/devnity/common/config/JwtConfig.java
  src/main/java/com/devnity/devnity/common/config/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/domain/auth/controller/AuthController.java
  src/main/java/com/devnity/devnity/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/devnity/devnity/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/Jwt.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthentication.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthenticationProvider.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthenticationToken.java
  src/main/java/com/devnity/devnity/domain/auth/service/AuthService.java
  src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
  src/main/java/com/devnity/devnity/domain/user/dto/UserDto.java
  src/main/java/com/devnity/devnity/domain/user/dto/response/UserInfoResponse.java
  src/main/java/com/devnity/devnity/domain/user/entity/Course.java
  src/main/java/com/devnity/devnity/domain/user/entity/Group.java
  src/main/java/com/devnity/devnity/domain/user/entity/GroupPermission.java
  src/main/java/com/devnity/devnity/domain/user/entity/Permission.java
  src/main/java/com/devnity/devnity/domain/user/entity/User.java
  src/main/java/com/devnity/devnity/domain/user/repository/CourseRepository.java
  src/main/java/com/devnity/devnity/domain/user/repository/GenerationRepository.java
  src/main/java/com/devnity/devnity/domain/user/repository/UserRepository.java
  src/main/java/com/devnity/devnity/domain/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/devnity/devnity/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/devnity/devnity/domain/auth/service/AuthServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/entity/UserTest.java
  src/test/java/com/devnity/devnity/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: 🎨 feat

#34 [Common-28] Exception 기능 정의
  .github/workflows/build-test.yml
  src/main/java/com/devnity/devnity/common/error/ErrorResponse.java
  src/main/java/com/devnity/devnity/common/error/GlobalExceptionHandler.java
  src/main/java/com/devnity/devnity/common/error/exception/BusinessException.java
  src/main/java/com/devnity/devnity/common/error/exception/EntityNotFoundException.java
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/common/error/exception/InvalidValueException.java
  src/main/java/com/devnity/devnity/common/utils/AwsS3UploaderTemp.java
  src/main/java/com/devnity/devnity/dummy/JsonRequest.java
  src/main/java/com/devnity/devnity/dummy/TestController.java
  src/main/java/com/devnity/devnity/dummy/TestService.java
Labels: 🎨 feat

#37 [Admin-35] 코스 API 구현
  src/main/java/com/devnity/devnity/domain/admin/controller/AdminCourseController.java
  src/main/java/com/devnity/devnity/domain/admin/controller/dto/CourseRequestDto.java
  src/main/java/com/devnity/devnity/domain/admin/controller/dto/CourseResponseDto.java
  src/main/java/com/devnity/devnity/domain/admin/repository/CourseRepository.java
  src/main/java/com/devnity/devnity/domain/admin/service/AdminCourseService.java
  src/main/java/com/devnity/devnity/domain/user/entity/Course.java
  src/test/java/com/devnity/devnity/domain/admin/controller/AdminCourseControllerTest.java
Labels: 🎨 feat

#44 [Common-20] CloudFront 적용 + JWT 환경변수 변경
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  deploy/dev/deploy.sh
  deploy/prod/deploy.sh
  src/docs/asciidoc/index.adoc
  src/main/java/com/devnity/devnity/common/utils/AwsS3UploaderTemp.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: ⚙ chore, 🔗 DevOps

#41 [Common-39] ErrorResponse클래스 서버시간 추가
  src/main/java/com/devnity/devnity/common/error/ErrorResponse.java
Labels: 🎨 feat

#46 [Common-42] RestDocs 도메인별 분리 설정
  src/docs/asciidoc/domain/admin.adoc
  src/docs/asciidoc/domain/auth.adoc
  src/docs/asciidoc/domain/error.adoc
  src/docs/asciidoc/domain/gathers.adoc
  src/docs/asciidoc/domain/images.adoc
  src/docs/asciidoc/domain/mapgakco.adoc
  src/docs/asciidoc/domain/users.adoc
  src/docs/asciidoc/index.adoc
  src/test/java/com/devnity/devnity/domain/admin/controller/AdminCourseControllerTest.java
Labels: ⚙ chore

#45 [User-23] 이메일 중복 확인 기능 구현
  src/main/java/com/devnity/devnity/common/config/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
  src/main/resources/application.yml
  src/test/java/com/devnity/devnity/domain/admin/controller/AdminCourseControllerTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
  src/test/java/com/devnity/devnity/dummy/TestControllerTest.java
Labels: 🎨 feat

#49 [User-48] 피드백 반영 & CORS 설정
  src/docs/asciidoc/domain/users.adoc
  src/main/java/com/devnity/devnity/common/config/WebMvcConfig.java
  src/main/java/com/devnity/devnity/common/config/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/domain/auth/controller/AuthController.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
  src/test/java/com/devnity/devnity/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
Labels: ⚙ chore, 🔧 refactor

#51 [Image-29]
  .github/workflows/deploy-prod.yml
  src/docs/asciidoc/domain/images.adoc
  src/docs/asciidoc/domain/media.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/devnity/devnity/common/utils/AwsS3Uploader.java
  src/main/java/com/devnity/devnity/common/utils/AwsS3UploaderTemp.java
  src/main/java/com/devnity/devnity/domain/media/controller/MediaController.java
  src/main/java/com/devnity/devnity/domain/media/dto/MediaUrlResponse.java
  src/main/java/com/devnity/devnity/domain/media/service/MediaService.java
  src/main/java/com/devnity/devnity/dummy/DummyImageRequest.java
  src/main/java/com/devnity/devnity/dummy/TestController.java
  src/main/java/com/devnity/devnity/dummy/TestService.java
  src/main/resources/application.yml
  src/test/java/com/devnity/devnity/domain/media/controller/MediaControllerTest.java
  src/test/java/com/devnity/devnity/dummy/TestControllerTest.java
  src/test/resources/application.yml
  src/test/resources/dummy.png
Labels: 🎨 feat, 💥 fix, 🔎 test

#52 [Common-50] SchedulerConfig 추가
  src/main/java/com/devnity/devnity/common/config/SchedulerConfig.java
Labels: 🎨 feat

#55 [Common-53] Mapgakco 도메인 BaseEntity 상속
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/Mapgakco.java
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoApplicant.java
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoComment.java
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoCommentStatus.java
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoStatus.java
Labels: 🎨 feat

#60 [Gather-26] 엔티티 양방향 매핑 설정
  .github/ISSUE_TEMPLATE.md
  build.gradle
  src/main/java/com/devnity/devnity/DevnityApplication.java
  src/main/java/com/devnity/devnity/common/config/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/common/entity/BaseEntity.java
  src/main/java/com/devnity/devnity/common/utils/AwsS3Uploader.java
  src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
  src/main/java/com/devnity/devnity/domain/gather/entity/GatherApplicant.java
  src/main/java/com/devnity/devnity/domain/gather/entity/GatherComment.java
  src/main/java/com/devnity/devnity/domain/media/controller/MediaController.java
  src/main/resources/data.sql
  src/test/java/com/devnity/devnity/EntityProvider.java
  src/test/java/com/devnity/devnity/domain/gather/repository/GatherRepositoryTest.java
  src/test/resources/application.yml
Labels: 🎨 feat, 🔎 test

#62 [User-24] 자기소개 저장(수정) 기능 구현
  src/main/java/com/devnity/devnity/common/config/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/domain/auth/controller/AuthController.java
  src/main/java/com/devnity/devnity/domain/introduction/entity/Introduction.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepository.java
  src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
  src/main/java/com/devnity/devnity/domain/user/entity/User.java
  src/main/java/com/devnity/devnity/domain/user/repository/CourseRepository.java
  src/main/java/com/devnity/devnity/domain/user/service/UserService.java
  src/test/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
  src/test/java/com/devnity/devnity/test/annotation/WithJwtAuthUser.java
  src/test/java/com/devnity/devnity/test/config/WithJwtAuthUserSecurityContext.java
Labels: 🎨 feat, ⚙ chore, 🔎 test

#54 [Common-31] CursorPageRequest, CursorPageResponse 추가
  src/main/java/com/devnity/devnity/common/api/CursorPageRequest.java
  src/main/java/com/devnity/devnity/common/api/CursorPageResponse.java
Labels: 🎨 feat

#81 [User-80] Rest docs 작성, 피드백 반영, 사용자 권한 변경
  src/docs/asciidoc/domain/users.adoc
  src/main/java/com/devnity/devnity/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/Jwt.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthenticationProvider.java
  src/main/java/com/devnity/devnity/domain/auth/jwt/JwtAuthenticationToken.java
  src/main/java/com/devnity/devnity/domain/auth/service/AuthService.java
  src/main/java/com/devnity/devnity/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/devnity/devnity/domain/user/entity/Authority.java
  src/main/java/com/devnity/devnity/domain/user/entity/Group.java
  src/main/java/com/devnity/devnity/domain/user/entity/GroupPermission.java
  src/main/java/com/devnity/devnity/domain/user/entity/Permission.java
  src/main/java/com/devnity/devnity/domain/user/entity/User.java
  src/main/java/com/devnity/devnity/domain/user/repository/CourseRepository.java
  src/main/java/com/devnity/devnity/domain/user/repository/GenerationRepository.java
  src/main/java/com/devnity/devnity/domain/user/repository/GroupRepository.java
  src/main/java/com/devnity/devnity/domain/user/service/UserService.java
  src/main/java/com/devnity/devnity/domain/user/service/UserServiceUtils.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/devnity/devnity/EntityProvider.java
  src/test/java/com/devnity/devnity/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/devnity/devnity/domain/auth/service/AuthServiceTest.java
  src/test/java/com/devnity/devnity/domain/gather/repository/GatherRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
  src/test/java/com/devnity/devnity/domain/user/entity/UserTest.java
  src/test/java/com/devnity/devnity/domain/user/repository/CourseRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/user/repository/GenerationRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/user/repository/GroupRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
  src/test/java/com/devnity/devnity/test/annotation/WithJwtAuthUser.java
  src/test/java/com/devnity/devnity/test/config/WithJwtAuthUserSecurityContext.java
  src/test/resources/application.yml
Labels: ⚙ chore, 🔧 refactor, 🔎 test

#82 [Media-61] 프로필 사진 업로드 API 추가 + S3 mocking 테스트 리팩토링
  src/docs/asciidoc/domain/media.adoc
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/common/error/exception/S3UploadException.java
  src/main/java/com/devnity/devnity/common/utils/AwsS3Uploader.java
  src/main/java/com/devnity/devnity/common/utils/AwsS3UploaderImpl.java
  src/main/java/com/devnity/devnity/domain/media/controller/MediaController.java
  src/main/java/com/devnity/devnity/domain/media/dto/ImageUrlResponse.java
  src/main/java/com/devnity/devnity/domain/media/service/MediaService.java
  src/main/java/com/devnity/devnity/dummy/TestService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-h2.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/devnity/devnity/domain/media/controller/MediaControllerTest.java
  src/test/java/com/devnity/devnity/test/config/MockAwsS3UploaderConfig.java
  src/test/java/com/devnity/devnity/test/provider/MediaProvider.java
Labels: 🎨 feat, 🔧 refactor, 🔎 test

#83 [User - 69] 메인페이지 자기소개 추천 기능 구현
  src/main/java/com/devnity/devnity/common/config/QueryDslConfig.java
  src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
  src/main/java/com/devnity/devnity/domain/introduction/dto/IntroductionDto.java
  src/main/java/com/devnity/devnity/domain/introduction/dto/response/SuggestResponse.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionService.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceUtils.java
  src/main/java/com/devnity/devnity/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/devnity/devnity/domain/user/entity/Authority.java
  src/main/java/com/devnity/devnity/domain/user/entity/User.java
  src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepository.java
  src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/user/repository/UserRepository.java
  src/main/java/com/devnity/devnity/domain/user/service/UserService.java
  src/main/java/com/devnity/devnity/domain/user/service/UserServiceUtils.java
  src/main/resources/data.sql
  src/test/java/com/devnity/devnity/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/devnity/devnity/domain/auth/service/AuthServiceTest.java
  src/test/java/com/devnity/devnity/domain/gather/repository/GatherRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionControllerTest.java
  src/test/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
  src/test/java/com/devnity/devnity/domain/user/entity/UserTest.java
  src/test/java/com/devnity/devnity/domain/user/repository/CourseRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/user/repository/GenerationRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
  src/test/java/com/devnity/devnity/test/annotation/WithJwtAuthUser.java
  src/test/java/com/devnity/devnity/test/config/TestConfig.java
  src/test/java/com/devnity/devnity/test/config/WithJwtAuthUserSecurityContext.java
Labels: 🎨 feat, ⚙ chore, 🔎 test

#84 [Admin-35] 코스 API PR 피드백 반영
  src/docs/asciidoc/domain/admin.adoc
  src/main/java/com/devnity/devnity/domain/admin/controller/AdminCourseController.java
  src/main/java/com/devnity/devnity/domain/admin/controller/dto/CourseRequest.java
  src/main/java/com/devnity/devnity/domain/admin/controller/dto/CourseResponse.java
  src/main/java/com/devnity/devnity/domain/admin/service/AdminCourseService.java
  src/test/java/com/devnity/devnity/domain/admin/controller/AdminCourseControllerTest.java
Labels: 🔧 refactor

#88 [User - 85] 리팩토링
  src/main/java/com/devnity/devnity/common/config/WebMvcConfig.java
  src/main/java/com/devnity/devnity/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/devnity/devnity/domain/config/annotation/UserId.java
  src/main/java/com/devnity/devnity/domain/config/resolver/UserIdResolver.java
  src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
  src/main/java/com/devnity/devnity/domain/introduction/exception/IntroductionNotFoundException.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCustomRepository.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepository.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceUtils.java
  src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
  src/main/java/com/devnity/devnity/domain/user/controller/UserIntroductionController.java
  src/main/java/com/devnity/devnity/domain/user/dto/request/SignUpRequest.java
  src/main/java/com/devnity/devnity/domain/user/entity/Authority.java
  src/main/java/com/devnity/devnity/domain/user/entity/User.java
  src/main/java/com/devnity/devnity/domain/user/entity/UserStatus.java
  src/main/java/com/devnity/devnity/domain/user/exception/CourseNotFoundException.java
  src/main/java/com/devnity/devnity/domain/user/exception/GenerationNotFoundException.java
  src/main/java/com/devnity/devnity/domain/user/exception/UserNotFoundException.java
  src/main/java/com/devnity/devnity/domain/user/repository/UserCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/user/service/UserService.java
  src/main/java/com/devnity/devnity/domain/user/service/UserServiceUtils.java
  src/main/java/com/devnity/devnity/domain/user/utils/annotation/Email.java
  src/main/java/com/devnity/devnity/domain/user/utils/annotation/Password.java
  src/main/java/com/devnity/devnity/domain/user/utils/annotation/UserName.java
  src/main/java/com/devnity/devnity/domain/user/utils/validator/EmailValidator.java
  src/main/java/com/devnity/devnity/domain/user/utils/validator/PasswordValidator.java
  src/main/java/com/devnity/devnity/domain/user/utils/validator/UserNameValidator.java
  src/test/java/com/devnity/devnity/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
  src/test/java/com/devnity/devnity/domain/user/dto/request/SignUpRequestTest.java
Labels: 🔧 refactor

#89 [Gather-64] 모집 게시글 등록 API 구현
  src/docs/asciidoc/domain/gathers.adoc
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
  src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherCategory.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherCommentStatus.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherStatus.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
  src/main/resources/data.sql
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
  src/test/java/com/devnity/devnity/domain/media/controller/MediaControllerTest.java
  src/test/java/com/devnity/devnity/test/provider/.keep
  src/test/java/com/devnity/devnity/test/provider/GatherProvider.java
  src/test/java/com/devnity/devnity/test/provider/TestHelper.java
Labels: 🎨 feat

#93 [Mapgakco-74] 맵각코 신청 API 구현
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/domain/mapgakco/Todo.txt
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoApplicantV1Controller.java
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetV1Controller.java
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoV1Controller.java
  src/main/java/com/devnity/devnity/domain/mapgakco/converter/MapgakcoApplicantConverter.java
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/Mapgakco.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoApplicantService.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoServiceUtils.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantService.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcocomment/MapgakcoCommentService.java
  src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoServiceTest.java
  src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantServiceTest.java
Labels: 🎨 feat

#92 [Gather-65] 모집 게시글 댓글 추가 API 구현
  src/docs/asciidoc/domain/gathers.adoc
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherApplicantController.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherCommentController.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherCommentRequest.java
  src/main/java/com/devnity/devnity/domain/gather/entity/GatherComment.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherCommentStatus.java
  src/main/java/com/devnity/devnity/domain/gather/exception/GatherCommentNotFoundException.java
  src/main/java/com/devnity/devnity/domain/gather/exception/GatherNotFoundException.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherCommentService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherServiceUtils.java
  src/main/resources/data.sql
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherCommentControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/repository/GatherRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/user/PasswordEncoderTest.java
  src/test/java/com/devnity/devnity/setting/provider/GatherProvider.java
  src/test/java/com/devnity/devnity/setting/provider/UserProvider.java
Labels: 🎨 feat, 🔎 test

#94 [Mapgakco-75] 맵각코 신청 취소 API 구현
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoApplicantV1Controller.java
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoV1Controller.java
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/Mapgakco.java
  src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoApplicantRepository.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantService.java
  src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantQueryMethodTest.java
  src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantServiceTest.java
Labels: 🎨 feat

#116 [Mapgakco-76] 맵각코 댓글 추가 API 구현
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/domain/mapgakco/Todo.txt
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetV1Controller.java
  src/main/java/com/devnity/devnity/domain/mapgakco/converter/MapgakcoCommentConverter.java
  src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakcocomment/request/.keep
  src/main/java/com/devnity/devnity/domain/mapgakco/dto/mapgakcocomment/request/MapgakcoCommentCreateRequest.java
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoComment.java
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoCommentStatus.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveService.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoServiceUtils.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoService.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantService.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcocomment/MapgakcoCommentService.java
  src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakco/MapgakcoServiceTest.java
  src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantServiceTest.java
Labels: 🎨 feat

#118 [Mapgakco-114] Provider 생성, test코드 수정
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoApplicantController.java
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetController.java
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcocomment/MapgakcoCommentService.java
  src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoApplicantControllerTest.java
  src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetControllerTest.java
  src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoControllerTest.java
  src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoV1ControllerTest.java
  src/test/java/com/devnity/devnity/domain/mapgakco/service/mapgakcoapplicant/MapgakcoApplicantQueryMethodTest.java
  src/test/java/com/devnity/devnity/setting/provider/MapgakcoProvider.java
Labels: 🔧 refactor, 🔎 test

#115 [User-109] 데둥이 소개 페이징 조회
  src/main/java/com/devnity/devnity/common/api/CursorPageRequest.java
  src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
  src/main/java/com/devnity/devnity/domain/introduction/dto/IntroductionDto.java
  src/main/java/com/devnity/devnity/domain/introduction/dto/request/SearchIntroductionRequest.java
  src/main/java/com/devnity/devnity/domain/introduction/dto/response/UserIntroductionResponse.java
  src/main/java/com/devnity/devnity/domain/introduction/entity/Introduction.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCommentRepository.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCustomRepository.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionLikeRepository.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionCommentService.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionLikeService.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionService.java
  src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
  src/main/java/com/devnity/devnity/domain/user/dto/request/SaveIntroductionRequest.java
  src/main/java/com/devnity/devnity/domain/user/dto/response/MyInfoResponse.java
  src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
  src/main/java/com/devnity/devnity/domain/user/service/UserService.java
  src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionControllerTest.java
  src/test/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
  src/test/java/com/devnity/devnity/domain/user/service/UserRetrieveServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
Labels: 🎨 feat, 🔧 refactor, 🔎 test

#119 [Mapgakco-78] 맵각코 댓글 삭제 API 구현
  src/main/java/com/devnity/devnity/domain/mapgakco/Todo.txt
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetController.java
  src/main/java/com/devnity/devnity/domain/mapgakco/entity/MapgakcoComment.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/mapgakcocomment/MapgakcoCommentService.java
  src/test/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommnetControllerTest.java
Labels: 🎨 feat

#122 [Gather-103] 모집 게시글 추천 조회 API 구현
  src/docs/asciidoc/domain/gathers.adoc
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherCommentController.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
  src/main/java/com/devnity/devnity/domain/gather/dto/GatherDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/GatherSimpleInfoDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/CreateGatherCommentResponse.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepository.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherCommentService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherRetrieveService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherCommentControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
Labels: 🎨 feat, 🔧 refactor, 🔎 test

#124 [Gather-104] 임시 PR
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
  src/main/java/com/devnity/devnity/domain/gather/dto/GatherCommentDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/GatherSubCommentDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/SimpleGatherInfoDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherCommentRequest.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/GatherDetailResponse.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/GatherStatusResponse.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/SuggestGatherResponse.java
  src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
  src/main/java/com/devnity/devnity/domain/gather/entity/GatherComment.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherCategory.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherCommentStatus.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherStatus.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherApplicantRepository.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCommentRepository.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherRetrieveService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
  src/main/java/com/devnity/devnity/domain/user/dto/SimpleUserInfoDto.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
Labels: ⚙ chore

#117 [Gather-67] 모집 게시글 메뉴바 조회 API 구현
  build.gradle
  src/docs/asciidoc/domain/gathers.adoc
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherCommentController.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
  src/main/java/com/devnity/devnity/domain/gather/dto/GatherCommentDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/GatherSubCommentDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/SimpleGatherInfoDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherCommentRequest.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/CreateGatherCommentResponse.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/GatherCardResponse.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/GatherDetailResponse.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/GatherStatusResponse.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/SuggestGatherResponse.java
  src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
  src/main/java/com/devnity/devnity/domain/gather/entity/GatherComment.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherCategory.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherCommentStatus.java
  src/main/java/com/devnity/devnity/domain/gather/entity/category/GatherStatus.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherApplicantRepository.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCommentRepository.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepository.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherCommentService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherRetrieveService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
  src/main/java/com/devnity/devnity/domain/user/dto/SimpleUserInfoDto.java
  src/test/java/com/devnity/devnity/EntityProvider.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherCommentControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/repository/GatherRepositoryTest.java
  src/test/java/com/devnity/devnity/setting/config/TestConfig.java
  src/test/java/com/devnity/devnity/setting/provider/GatherProvider.java
Labels: 🎨 feat, 🔎 test

#123 [User - 111] 데둥이 소개 상세 조회 구현
  build.gradle
  src/docs/asciidoc/domain/introductions.adoc
  src/main/java/com/devnity/devnity/domain/auth/controller/AuthController.java
  src/main/java/com/devnity/devnity/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
  src/main/java/com/devnity/devnity/domain/introduction/dto/IntroductionCommentDto.java
  src/main/java/com/devnity/devnity/domain/introduction/dto/IntroductionDto.java
  src/main/java/com/devnity/devnity/domain/introduction/dto/response/UserDetailIntroductionResponse.java
  src/main/java/com/devnity/devnity/domain/introduction/entity/IntroductionComment.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionCommentRepository.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/IntroductionRepository.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCommentCustomRepository.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCommentCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCustomRepository.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionCommentService.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionLikeService.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionService.java
  src/main/resources/data.sql
  src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionCommentControllerTest.java
  src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionControllerTest.java
  src/test/java/com/devnity/devnity/domain/introduction/respository/IntroductionCommentRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionCommentServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
Labels: 🎨 feat, 🔎 test

#127 [Gather-125] 내가 등록/신청한 모집 조회 추가 (GatherRetrieveService)
  src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherApplicantRepository.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherRepository.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherRetrieveService.java
Labels: 🎨 feat

#130 [User - 111] 리팩토링
  src/main/java/com/devnity/devnity/common/api/CursorPageRequest.java
  src/main/java/com/devnity/devnity/common/error/GlobalExceptionHandler.java
  src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCustomRepositoryImpl.java
Labels: 🔧 refactor

#134 [User] 내가 모집한 모임 & 신청한 모임 관리 기능 구현
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepository.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherRetrieveService.java
  src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
  src/main/java/com/devnity/devnity/domain/introduction/entity/Introduction.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionService.java
  src/main/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceUtils.java
  src/main/java/com/devnity/devnity/domain/mapgakco/converter/MapgakcoConverter.java
  src/main/java/com/devnity/devnity/domain/mapgakco/dto/SimpleMapgakcoInfoDto.java
  src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoCustomRepository.java
  src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoRepository.java
  src/main/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveService.java
  src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
  src/main/java/com/devnity/devnity/domain/user/dto/response/UserGathersResponse.java
  src/main/java/com/devnity/devnity/domain/user/entity/User.java
  src/main/java/com/devnity/devnity/domain/user/service/UserRetrieveService.java
  src/main/java/com/devnity/devnity/domain/user/service/UserService.java
  src/main/java/com/devnity/devnity/domain/user/service/UserServiceUtils.java
  src/test/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/gather/service/GatherRetrieveServiceTest.java
  src/test/java/com/devnity/devnity/domain/mapgakco/repository/MapgakcoCustomRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/mapgakco/service/MapgakcoRetrieveServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
  src/test/java/com/devnity/devnity/domain/user/service/IntroDto.java
  src/test/java/com/devnity/devnity/domain/user/service/TransactionTest.java
  src/test/java/com/devnity/devnity/domain/user/service/UserRetrieveServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
  src/test/java/com/devnity/devnity/setting/config/TestConfig.java
  src/test/java/com/devnity/devnity/setting/provider/UserProvider.java
Labels: 🎨 feat, 🔧 refactor, 🔎 test

#136 [Gather-107] 댓글 수정 API 구현 및 프론트엔드 시간 포맷 피드백 반영
  src/docs/asciidoc/domain/gathers.adoc
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherCommentController.java
  src/main/java/com/devnity/devnity/domain/gather/dto/GatherChildCommentDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/GatherCommentDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/SimpleGatherInfoDto.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/UpdateGatherCommentRequest.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/UpdateGatherRequest.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/CreateGatherCommentResponse.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/GatherDetailResponse.java
  src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
  src/main/java/com/devnity/devnity/domain/gather/entity/GatherComment.java
  src/main/java/com/devnity/devnity/domain/gather/entity/vo/Deadline.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherCommentService.java
  src/test/java/com/devnity/devnity/domain/gather/TimeTest.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherApplicantControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherCommentControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/service/GatherRetrieveServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
  src/test/java/com/devnity/devnity/domain/user/service/UserServiceTest.java
  src/test/java/com/devnity/devnity/setting/provider/GatherProvider.java
Labels: 🎨 feat, 🔧 refactor, 🔎 test

#142 [Gather-107] 모집 게시글 댓글 삭제 API 구현
  src/docs/asciidoc/domain/gathers.adoc
  src/main/java/com/devnity/devnity/common/config/WebMvcConfig.java
  src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/common/utils/HealthController.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherCommentController.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/UpdateGatherRequest.java
  src/main/java/com/devnity/devnity/domain/gather/dto/response/DeleteGatherCommentResponse.java
  src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
  src/main/java/com/devnity/devnity/domain/gather/entity/GatherComment.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherCommentService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
  src/main/java/com/devnity/devnity/domain/user/dto/SimpleUserInfoDto.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherApplicantControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherCommentControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
Labels: 🎨 feat, 🔎 test

#98 [Admin-35] 코스 수정 request 수정
  src/main/java/com/devnity/devnity/domain/admin/controller/AdminCourseController.java
  src/main/java/com/devnity/devnity/domain/admin/service/AdminCourseService.java
Labels: 🔧 refactor

#146 [Gather-138] 모집 마감 API 구현 및 Spring Scheduler 적용
  src/docs/asciidoc/domain/gathers.adoc
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
  src/main/java/com/devnity/devnity/domain/gather/dto/SimpleGatherInfoDto.java
  src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepository.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherApplicantService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherCommentService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherRetrieveService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherUtilService.java
  src/main/java/com/devnity/devnity/domain/gather/utils/event/CreateGatherApplicantEvent.java
  src/main/java/com/devnity/devnity/domain/gather/utils/event/CreateGatherCommentEvent.java
  src/main/java/com/devnity/devnity/domain/gather/utils/event/DeleteGatherApplicationEvent.java
  src/main/java/com/devnity/devnity/domain/gather/utils/event/DeleteGatherCommentEvent.java
  src/main/java/com/devnity/devnity/domain/gather/utils/event/GatherEvent.java
  src/main/java/com/devnity/devnity/domain/gather/utils/event/GatherEventHandler.java
  src/main/java/com/devnity/devnity/domain/gather/utils/scheduler/GatherScheduler.java
  src/main/resources/application-dev.yml
  src/main/resources/application-h2.yml
  src/main/resources/application-prod.yml
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/repository/GatherRepositoryTest.java
Labels: 🎨 feat, 🔎 test

#140 [User - 135] 인증 및 인가 관련 예외 처리
  src/main/java/com/devnity/devnity/common/config/WebMvcConfig.java
  src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/common/config/security/annotation/UserId.java
  src/main/java/com/devnity/devnity/common/config/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/devnity/devnity/common/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/devnity/devnity/common/config/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/devnity/devnity/common/config/security/resolver/UserIdResolver.java
  src/main/java/com/devnity/devnity/common/error/AuthErrorResponse.java
  src/main/java/com/devnity/devnity/common/error/GlobalExceptionHandler.java
  src/main/java/com/devnity/devnity/common/error/JwtAccessDeniedHandler.java
  src/main/java/com/devnity/devnity/common/error/exception/AuthErrorCode.java
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/domain/auth/service/AuthService.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherApplicantController.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherCommentController.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
  src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionCommentController.java
  src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionController.java
  src/main/java/com/devnity/devnity/domain/introduction/controller/IntroductionLikeController.java
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoApplicantController.java
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoCommentController.java
  src/main/java/com/devnity/devnity/domain/mapgakco/controller/MapgakcoController.java
  src/main/java/com/devnity/devnity/domain/user/controller/UserController.java
  src/main/java/com/devnity/devnity/domain/user/entity/User.java
  src/test/java/com/devnity/devnity/domain/user/entity/UserTest.java
Labels: 🎨 feat, 🔎 test

#101 [Admin-99] 초대 링크 API
  src/docs/asciidoc/domain/admin.adoc
  src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/domain/admin/controller/AdminCourseController.java
  src/main/java/com/devnity/devnity/domain/admin/controller/AdminGenerationController.java
  src/main/java/com/devnity/devnity/domain/admin/controller/AdminInvitationController.java
  src/main/java/com/devnity/devnity/domain/admin/controller/dto/CourseRequest.java
  src/main/java/com/devnity/devnity/domain/admin/controller/dto/GenerationRequest.java
  src/main/java/com/devnity/devnity/domain/admin/controller/dto/GenerationResponse.java
  src/main/java/com/devnity/devnity/domain/admin/dto/InvitationDto.java
  src/main/java/com/devnity/devnity/domain/admin/dto/request/CourseRequest.java
  src/main/java/com/devnity/devnity/domain/admin/dto/request/GenerationRequest.java
  src/main/java/com/devnity/devnity/domain/admin/dto/request/InvitationRequest.java
  src/main/java/com/devnity/devnity/domain/admin/dto/response/CourseResponse.java
  src/main/java/com/devnity/devnity/domain/admin/dto/response/GenerationResponse.java
  src/main/java/com/devnity/devnity/domain/admin/dto/response/InvitationResponse.java
  src/main/java/com/devnity/devnity/domain/admin/entity/Invitation.java
  src/main/java/com/devnity/devnity/domain/admin/repository/InvitationRepository.java
  src/main/java/com/devnity/devnity/domain/admin/service/AdminCourseService.java
  src/main/java/com/devnity/devnity/domain/admin/service/AdminGenerationService.java
  src/main/java/com/devnity/devnity/domain/admin/service/AdminInvitationService.java
  src/main/java/com/devnity/devnity/domain/admin/utils/AdminScheduler.java
  src/main/java/com/devnity/devnity/domain/base/vo/Deadline.java
  src/main/java/com/devnity/devnity/domain/gather/entity/Gather.java
  src/main/java/com/devnity/devnity/domain/gather/entity/GatherComment.java
  src/main/java/com/devnity/devnity/domain/introduction/entity/Introduction.java
  src/main/java/com/devnity/devnity/domain/user/entity/Course.java
  src/main/java/com/devnity/devnity/domain/user/entity/Generation.java
  src/test/java/com/devnity/devnity/domain/admin/controller/AdminCourseControllerTest.java
  src/test/java/com/devnity/devnity/domain/admin/controller/AdminGenerationControllerTest.java
  src/test/java/com/devnity/devnity/domain/admin/controller/AdminInvitationControllerTest.java
  src/test/java/com/devnity/devnity/domain/admin/repository/InvitationRepositoryTest.java
  src/test/java/com/devnity/devnity/domain/base/BaseEntityTest.java
  src/test/java/com/devnity/devnity/setting/provider/GatherProvider.java
Labels: 🎨 feat, 🔎 test

#161 [User] CORS 에러 해결
  src/main/java/com/devnity/devnity/common/config/WebMvcConfig.java
  src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
Labels: 💥 fix

#166 [User] MBTI 오타 수정
  src/main/java/com/devnity/devnity/DevnityApplication.java
  src/main/java/com/devnity/devnity/domain/user/entity/Mbti.java
  src/main/resources/data.sql
  src/test/java/com/devnity/devnity/domain/introduction/controller/IntroductionControllerTest.java
  src/test/java/com/devnity/devnity/domain/introduction/service/IntroductionServiceTest.java
  src/test/java/com/devnity/devnity/domain/user/controller/UserControllerTest.java
Labels: 💥 fix

#168 [Gather-153] 모집 페이징 조회 API - 검색 기능 추가
  README.md
  src/docs/asciidoc/domain/admin.adoc
  src/docs/asciidoc/domain/gathers.adoc
  src/main/java/com/devnity/devnity/common/error/exception/ErrorCode.java
  src/main/java/com/devnity/devnity/domain/admin/controller/AdminInvitationController.java
  src/main/java/com/devnity/devnity/domain/admin/entity/Invitation.java
  src/main/java/com/devnity/devnity/domain/admin/repository/InvitationRepository.java
  src/main/java/com/devnity/devnity/domain/admin/scheduler/AdminScheduler.java
  src/main/java/com/devnity/devnity/domain/admin/service/AdminInvitationService.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
  src/main/java/com/devnity/devnity/domain/gather/event/CreateGatherApplicantEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/CreateGatherCommentEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/DeleteGatherApplicationEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/DeleteGatherCommentEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/GatherEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/GatherEventHandler.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepository.java
  src/main/java/com/devnity/devnity/domain/gather/repository/GatherCustomRepositoryImpl.java
  src/main/java/com/devnity/devnity/domain/gather/scheduler/GatherScheduler.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherApplicantService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherCommentService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
  src/test/java/com/devnity/devnity/domain/admin/controller/AdminInvitationControllerTest.java
  src/test/java/com/devnity/devnity/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/controller/GatherControllerTest.java
  src/test/java/com/devnity/devnity/domain/gather/repository/GatherRepositoryTest.java
  src/test/java/com/devnity/devnity/setting/config/TestConfig.java
  src/test/java/com/devnity/devnity/setting/config/WithJwtAuthUserSecurityContext.java
  src/test/java/com/devnity/devnity/setting/provider/GatherProvider.java
  src/test/java/com/devnity/devnity/setting/provider/TestHelper.java
Labels: 🔧 refactor, 🔎 test

#169 [Auth] Invitation 엔티티 수정
  src/main/java/com/devnity/devnity/domain/admin/controller/AdminInvitationController.java
  src/main/java/com/devnity/devnity/domain/admin/dto/InvitationDto.java
  src/main/java/com/devnity/devnity/domain/admin/entity/Invitation.java
  src/main/java/com/devnity/devnity/domain/admin/repository/InvitationRepository.java
  src/main/java/com/devnity/devnity/domain/admin/service/AdminInvitationService.java
  src/main/java/com/devnity/devnity/domain/admin/service/AdminRetrieveService.java
  src/main/java/com/devnity/devnity/domain/auth/controller/AuthController.java
  src/main/java/com/devnity/devnity/domain/auth/service/AuthService.java
  src/test/java/com/devnity/devnity/domain/auth/controller/AuthControllerTest.java
Labels: 💥 fix

#172 [Common-171] 프로필별 CORS 허용 origin 분리
  src/main/java/com/devnity/devnity/common/api/health/HealthController.java
  src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/common/config/security/cors/CorsConfig.java
  src/main/java/com/devnity/devnity/domain/admin/scheduler/AdminScheduler.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: ⚙ chore

#182 [Gather-171] CORS 허용 origin 분리 + 모집 등록시 Slack 알람 기능 구현
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  build.gradle
  deploy/dev/deploy.sh
  deploy/prod/deploy.sh
  src/main/java/com/devnity/devnity/common/config/security/WebSecurityConfig.java
  src/main/java/com/devnity/devnity/common/utils/annotation/ApplicantLimit.java
  src/main/java/com/devnity/devnity/common/utils/validator/ApplicantLimitValidator.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
  src/main/java/com/devnity/devnity/domain/gather/event/CreateGatherApplicantEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/CreateGatherCommentEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/CreateGatherEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/DeleteGatherApplicationEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/DeleteGatherCommentEvent.java
  src/main/java/com/devnity/devnity/domain/gather/event/GatherEventHandler.java
  src/main/java/com/devnity/devnity/domain/gather/event/SimpleGatherEvent.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherService.java
  src/main/java/com/devnity/devnity/domain/gather/service/GatherUtilService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🎨 feat, ⚙ chore

#184 [User] 서브 댓글 정렬 변경
  src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCommentCustomRepositoryImpl.java
Labels: 🔧 refactor

#192 [Release] v1.0.0 Beta bug fix
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherCommentController.java
  src/main/java/com/devnity/devnity/domain/gather/controller/GatherController.java
  src/main/java/com/devnity/devnity/domain/gather/dto/request/CreateGatherRequest.java
  src/main/java/com/devnity/devnity/domain/introduction/respository/custom/IntroductionCustomRepositoryImpl.java
Labels: 💥 fix
